url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Pool Demo" # the name of your site, e.g. ACME Corp.
author: "Dan Carroll"
copyright: "2023"